### ISSUE TITLE
[NIAC 2018 Proposals] Add NXdiffractometer or NXgoniometer to NXinstrument

### ISSUE THREAD

**Issue by vasole** [nexusformat/NIAC#26] opened 2018-03-12 15:10 UTC
Rationale
======

Diffractometers are relatively common instruments and a very common operation is the conversion from data to Q or reciprocal space based on the position of the motors associated to the diffractometer. Currently one has to look for all the positioners in an entry to find the common mnemonics used as function of the diffractometer geometry (phi, chi, theta, twotheta, mu, delta, ...).

Proposal
---------

- Define a new base class NXdiffractometer to be added to NXinstrument family.
- Provide the name of the implemented geometry. We could rely on articles and/or the names used by other software like SPEC for the geometry name and/or the motor names in order not to reinvent the wheel.
- Provide the reference (or the URL) where the geometry is described. I would start defining the classics:

   - W.R. Busing and H.A. Levy. Acta Cryst. 22 (1967) 457-464. (aka. FOURC)
   - M. Lohmeier and E. Vlieg. J. Appl. Cryst. 26 (1993) 706-716 (aka. SIXC)
   - H. You J. Appl. Cryst. 55 (1999) 614-623 (aka. 4S+2D or PSIC)      

and let the community to enlarge the list with the different variants.

I think we have enough time to contact the diffractometer users at our respective facilities for their feedback prior to the NIAC meeting.

**Comment by mkoennecke** [comment] 2018-03-16 14:01
Hmm, this looks very much like what a NXtransformations group in NXsample and may be NXdetector covers. May be, the only thing required is a clarification how this is used in the context of those different diffractometers.

**Comment by rayosborn** [comment] 2018-03-16 16:34
@mkoennecke, I think the problem is that the NXtransformations class is entirely abstract. It's a method for linking angles, but there is no specification for what to call the goniometer pitch or the chi angle or the detector yaw, pitch and roll. In our (private) implementation of crystal orientation software, I created a NXgoniometer class, in the spirit of what Armando is proposing, with references back to Busing and Levy, etc. I think something like this would be welcomed by a lot of crystallographers.

**Comment by vasole** [comment] 2018-03-16 17:56
As Ray points out,  NXtransformations is not an "Instrument" while a diffractometer is is actually an instrument in the proper sense of the term and, in my opinion, just because of that it already deserves its class under NXinstrument.

If it can be presented as an instrument containing a positioners group with the actual motors and a transformation group, that is a solution as good to me as any other solution.

**Comment by prjemian** [comment] 2018-10-25 18:20
closing since [definitions issue](https://github.com/nexusformat/definitions/issues/632) has been created

**Closed by prjemian** 2018-10-25 18:20 UTC
